version: '3'
services:
  wordpress:
    image: "wordpress:${WORDPRESS_IMAGE}" # https://hub.docker.com/_/wordpress/
    ports:
      - "${WORDPRESS_PORT}:80"
    volumes:
      - ".:/var/www/html/wp-content/plugins/${WORDPRESS_PLUGIN_NAME}" # Plugin development
      - ./docker/wordpress:/var/www/html # WordPress core
    environment:
      WORDPRESS_DB_HOST: "database:${DATABASE_PORT}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
    depends_on:
      - database
  database:
    image: "${DATABASE_FLAVOR}:latest"
    ports:
      - "${DATABASE_PORT}:3306"
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./docker/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${WORDPRESS_DB_NAME}"
      MYSQL_USER: "${WORDPRESS_DB_USER}"
      MYSQL_PASSWORD: "${WORDPRESS_DB_PASSWORD}"